[package]
name = "egressd-orchestrator"
version.workspace = true
edition.workspace = true

[dependencies]
egressd-core = { path = "../egressd-core" }
tokio = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
bollard = { workspace = true }
rand = { workspace = true }
