name: ci
on:
  push:
    branches: [main, master, develop, features, fixes, chores]
  pull_request:
    branches: [main, master, develop, features, fixes, chores, "feat/**", "fix/**"]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo test
